### ISSUE TITLE
some module l can't find ,help me

### ISSUE THREAD

**Issue by kesss124** [adobe-research/MetaAF#13]
1.Traceback (most recent call last):
  File "/home/easymoney/kk/MetaAF/metaaf/core.py", line 6, in <module>
    from metaaf.optimizer_utils import FeatureContainer
ModuleNotFoundError: No module named 'metaaf'
2.ModuleNotFoundError                       Traceback (most recent call last)
/home/easymoney/kk/MetaAF/examples/sysid_demo.ipynb Cell 1 line 1
----> <a href='[vscode-notebook-cell://wsl%2Bubuntu-22.04/home/easymoney/kk/MetaAF/examples/sysid_demo.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'>1</a>](vscode-notebook-cell://wsl%2Bubuntu-22.04/home/easymoney/kk/MetaAF/examples/sysid_demo.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'%3E1%3C/a%3E) get_ipython().run_line_magic('load_ext', 'lab_black')
      <a href='[vscode-notebook-cell://wsl%2Bubuntu-22.04/home/easymoney/kk/MetaAF/examples/sysid_demo.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1'>2</a>](vscode-notebook-cell://wsl%2Bubuntu-22.04/home/easymoney/kk/MetaAF/examples/sysid_demo.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1'%3E2%3C/a%3E) get_ipython().run_line_magic('load_ext', 'autoreload')
      <a href='[vscode-notebook-cell://wsl%2Bubuntu-22.04/home/easymoney/kk/MetaAF/examples/sysid_demo.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2'>3</a>](vscode-notebook-cell://wsl%2Bubuntu-22.04/home/easymoney/kk/MetaAF/examples/sysid_demo.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2'%3E3%3C/a%3E) get_ipython().run_line_magic('autoreload', '2')

File [~/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2432](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/easymoney/kk/MetaAF/examples/~/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2432), in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2430     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2431 with self.builtin_trap:
-> 2432     result = fn(*args, **kwargs)
   2434 # The code below prevents the output from being displayed
   2435 # when using magics with decorator @output_can_be_silenced
   2436 # when the last Python token in the expression is a ';'.
   2437 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File [~/.local/lib/python3.10/site-packages/IPython/core/magics/extension.py:33](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/easymoney/kk/MetaAF/examples/~/.local/lib/python3.10/site-packages/IPython/core/magics/extension.py:33), in ExtensionMagics.load_ext(self, module_str)
     31 if not module_str:
     32     raise UsageError('Missing module name.')
---> 33 res = self.shell.extension_manager.load_extension(module_str)
     35 if res == 'already loaded':
     36     print("The %s extension is already loaded. To reload it, use:" % module_str)

File [~/.local/lib/python3.10/site-packages/IPython/core/extensions.py:76](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/easymoney/kk/MetaAF/examples/~/.local/lib/python3.10/site-packages/IPython/core/extensions.py:76), in ExtensionManager.load_extension(self, module_str)
     69 """Load an IPython extension by its module name.
...
File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1004, in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'lab_black

**Comment by jmcasebeer** [comment]
The demo uses black for code formatting. Looks like you're missing the jupyter lab version. You can find install instructions [here](https://github.com/dnanhkhoa/nb_black).

**Comment by kesss124** [comment]
This module was my last hurdle, I searched for a long time without finding
it, and when I ran core.py.
Terminal display:
Traceback (most recent call last):
  File "/home/easymoney/kk/MetaAF/metaaf/core.py", line 6, in <module>
    from metaaf.optimizer_utils import FeatureContainer
ModuleNotFoundError: No module named 'metaaf'

Jonah Casebeer ***@***.***> 于2023年9月15日周五 23:55写道：
