### ISSUE TITLE
I've got a few ideas.

### ISSUE THREAD

**Issue by lvyuhhh** [adobe-research/MetaAF#15]
I have an idea  that change your specialised focus on linear FD adaptive filters to non-linear adaptive filters and use  for continuous signals, I don't know if it's possible, I hope you can answer my confusion.If so, what should I do to improve.thanks

**Comment by jmcasebeer** [comment]
That sounds like an interesting idea and should be possible with the current framework. A good place to start would be implementing a nonlinear filter in Haiku.

**Comment by lvyuhhh** [comment]
Oh, thank you very much for your answer, also I was thinking to combine this code with matlab, what do you think?
