### ISSUE TITLE
Compatibility with x64 CPU

### ISSUE THREAD

**Issue by Toplica001** [adobe-research/MetaAF#19]
Hello, I have AMD graphics card and i can't install JAX because it is not available for windows on AMD GPUs, is this program compatible with x64 based CPUs or just x86? I have installed JAX for CPU and i just want to know if it is compatible?

**Comment by jmcasebeer** [comment]
Hello!

Our compatibility should match whatever JAX has. You should check the JAX repository [here](https://github.com/google/jax?tab=readme-ov-file#installation). Hope that helps!

**Comment by Toplica001** [comment]
Ok, thank you
