### ISSUE TITLE
The replicate results don't match the demo.

### ISSUE THREAD

**Issue by quizt35** [adobe-research/MetaAF#21]
Hello! Thanks for sharing the pre-trained models and demos. 
I would like to replicate the demo results using a pretrained model. I used the data from the first row of the double-talk and converted the mp3 to wav format (single channel, 16000Hz, 16bit) for convenience. Based on the speech titles downloaded from the demo page, I selected the same pkl file to process the original speech. However, there is a significant difference between the spectrograms from the demo page and those generated using the pre-trained model. I've checked every steps and can't find the reason. Could you help me understand why?

<img width="308" alt="1715424116578" src="https://github.com/adobe-research/MetaAF/assets/22266618/a3ab12b9-6dc7-4b41-b799-025166cd403c">
<img width="317" alt="1715424077930" src="https://github.com/adobe-research/MetaAF/assets/22266618/1ee0be33-ee94-442b-b40d-dc434c840507">

model tag: v1.0.1
This code i used is below:

```
import os
from aec_eval import get_system_ckpt
import numpy as np
import librosa
import soundfile as sf

ckpt_dir = "v1.0.1_models/aec/"
name = "meta_aec_16_combo_rl_4_1024_512_r2"
date = "2022_10_19_23_43_22"
epoch = 110

ckpt_loc = os.path.join(ckpt_dir, name, date)

system, kwargs, outer_learnable = get_system_ckpt(
    ckpt_loc,
    epoch,
)
fit_infer = system.make_fit_infer(outer_learnable=outer_learnable)
fs = 16000

out_dir = "metaAF_output"
os.makedirs(out_dir, exist_ok=True)

u, _ = librosa.load("u.wav", sr=fs)
d, _ = librosa.load("d.wav", sr=fs)
s, _ = librosa.load("s.wav", sr=fs)
e = d - s

d_input = {"u": u[None, :, None], "d": d[None, :, None],
           "s": s[None, :, None], "e": e[None, :, None]
           }
pred = system.infer({"signals": d_input, "metadata": {}}, fit_infer=fit_infer)[0]
pred = np.array(pred[0, :, 0])

sf.write(os.path.join(out_dir, f"_out.wav"), pred, fs)
```

Looking forward to hearing from you, thanks!

**Comment by jmcasebeer** [comment]
Hello and thanks for the question. 

The demo files are all rescaled to [-1, 1] for playback (see website footnote), which is not how the AEC data was setup for training. A previous github issue [here](https://github.com/adobe-research/MetaAF/issues/4#issuecomment-1166251110) noted this issue as well and rescaled `d = d / 10`.

If you want to replicate my results fully, I would recommend downloading the data from the AEC challenge and using that.

**Comment by quizt35** [comment]
Thanks for your reply. By setting a scale, I can get a more reasonable result, but there are still some minor issues. As shown in the figure below, there are similar impulses in the first few seconds of the speech. I'm wondering if this is due to the window or the format of the original speech. I will also follow your suggestion to test on the AEC Challenge datasets.
<img width="214" alt="1715654928043" src="https://github.com/adobe-research/MetaAF/assets/22266618/fb37a058-67b5-4425-beea-40a207e0d600">

**Comment by quizt35** [comment]
Additionally, should the URL for JAX in the ‘ReadMe - GPU Setup’ be https://storage.googleapis.com/jax-releases/jax_cuda_releases.html?
