### ISSUE TITLE
About experiments on non-audio tasks

### ISSUE THREAD

**Issue by greeted** [adobe-research/MetaAF#23]
Could you please provide the detailed code for "Appendix A: Experiments on Non-Audio Tasks" from your doctoral thesis? Thank you!
![image](https://github.com/user-attachments/assets/ebb0943b-6ce9-4433-b981-2b17b5adbe0b)

**Comment by Kami-prog** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by jmcasebeer** [comment]
Hello!

Can you please send me an email at jonah.casebeer@ieee.org? I'll share the jupyter notebook and code for the plots. These are toy experiments and I don't want to clutter this repo with them.
